### ISSUE TITLE
wallet not-connected

### ISSUE THREAD

**Issue by mjeckley** [doged/electrum-doged#12] opened 2017-12-23 18:59 UTC
I've used 5 different addresses; not connecting, sending XVG from binance...?

suggestions?

**Comment by revizionary1** [comment] 2017-12-24 20:18
Did anyone get back to you? This is ridiculous...I am having the same issue. I downloaded the Verge blockchain which contains no exe or app to extract from the zip file and no instructions on how to sync with Windows. I am having the same issue and there are Verge XVG I had sent to my wallet from Changelly which are not showing up because the wallet is still not online. I have no idea how to verify where it is on the blockchain because get the zip file to extract properly. I have a Lisk Nano wallet and other wallets and they were seamless. This wallet (The Electrum) is unbelievably bad. How is this user friendly. What company releases a product with all of these glitches? It is very easy to release a wallet that syncs to the network a user is using. Very, very easy to write that code.

**Comment by darknessOverwhelming** [comment] 2017-12-24 20:57
Connected to elec2.verge-blockchain.com this morning. Transferred coins into wallet. Did not work the rest of the day. Reading around heard maybe it is a capacity? I am just continuing to keep trying maybe it is better at evening or morning.

**Comment by SebastianBoldt** [comment] 2017-12-25 00:29
Did not work for me too. Tried all suggested servers from the internet. It is also not possible to delete servers added once .. this all feels beta as f***. I am running 2.4 on a Mac.

**Comment by revizionary1** [comment] 2017-12-25 00:30
Thanks...I got my coins in my wallet somehow about an hour or so ago.

I used the roaming update...I will try your link to see if I can get my
wallet to connect at a more regular interval. What is it with this? My Lisk
Nano wallet seamlessly connects. Perhaps a statement on the engineering
behind Lisk and Verge?

**Comment by justinvforvendetta** [comment] 2017-12-25 00:40
we posted 2 new electrum servers on the twitter a few hours ago, and we have several more syncing right now. also, we'll have a website up in the next few days with a list of active servers. eventually we will move all of our electrum support to the tor electrum.

**Closed as completed by justinvforvendetta** 2017-12-25 00:40 UTC

**Comment by revizionary1** [comment] 2017-12-25 00:54
Amen. I hear that...

It is not like I don't know computers. I have been working on them since
the late 1990s and then went to law school. I am computer literate and I am
sure you are too. I have Bitcoin and Nano Wallets and a Core Wallet.

This stuff makes the old Windows Beta releases look like a streamlined
success. I used to always wait a year or two before buying any new MS OS.
The thing is, with these crypto speculative ventures and blockchain, if you
snooze, you lose. They know this...

In the end they will be the losers because the public will only go with
Coinbase type stuff that is very user friendly, or huge businesses will
gravitate to Ripple and Lisk.

**Comment by revizionary1** [comment] 2017-12-25 00:55
Anything is better than what is being used now. Keep us updated.

**Comment by justinvforvendetta** [comment] 2017-12-25 01:09
uhmm @revizionary1 what exactly is the issue? also, in general, windows is a terrible platform for privacy software, linux being ideal. lisk is of course, not geared toward privacy. neither is ripple. the new electrum servers we posted from twitter earlier today are nowhere near full either, and we have 3 more coming up right now.

**Comment by darknessOverwhelming** [comment] 2017-12-25 01:15
Just worked now.

**Comment by mjeckley** [comment] 2017-12-25 05:57
Turn off SSL

**Comment by revizionary1** [comment] 2017-12-25 20:43
The issue is that the zip file does not extract a fully loadable platform
(with an app or exe file) for the blockchain, and the wallet does not stay
online. It synced for about 20 minutes and is offline and will not
reconnect. I have a Lisk Nano wallet and a Electroneum Wallet. And a
Bitcoin Core wallet. No issues at all with them...they are seamless. And in
WINDOWS no less. They have minor issues, but nothing like Verge's
blockchain zip files or the Wallets they use. Understand?

**Comment by justinvforvendetta** [comment] 2017-12-25 21:19
@revizionary1 this is an electrum wallet which doesn't require downloading/syncing a blockchain. also these wallets connect to electrum servers. lately the servers the have listed by default have been completely full of users. anyone who has tried the 2 servers someone put up yesterday said they connected immediately.

**Comment by revizionary1** [comment] 2017-12-26 10:11
No...I realize they do not need a blockchain. They do not, however, connect
to Electrum servers. They connect to elec2.verge.blockchain.com servers.
Special servers for Verge.

It is a totally different server than the ones my Electrum Bitcoin or
Electrum TRN run on. And those two stay connected whenever you click them
on and they then sync.

**Comment by revizionary1** [comment] 2017-12-26 10:15
I did get it connected to the elec2 server BTW. It goes on and off...but it
does connect. It is The address I gave in my last email and you have to
change 50002 to 50003. It does work, somewhat. It still in not seamless and
my server goes off more than it is on but it does go on from time to time.

Regardless, this is 2018 almost. You simply get it right the first time and
stop Beta testing on the market. It is not hard to connect to a server from
a computer. It is child's play for any programmer. Well, almost...
